// Handlers for user routes

import express, { Request, Response } from 'express';
import { User, UserStore, UserWithID } from '../models/user';
import jwt from 'jsonwebtoken';
import { verifyAuthToken } from '../middleware/verification';

// Create a new store object of the UserStore class to use its methods in the handler functions below
const store = new UserStore();

// Handler functions here

/**
 * Shows all users from the store 
 * 
 * @param {Request} _req - The request object (unused)
 * @param {Response} res - The response object used to send the users information
 */
const index = async (_req: Request, res: Response) => {
  try {
    // Call the index method of the store object to get all users
    const users = await store.index();
    // Send the users as a response
    res.json(users);
  } catch (err) {
    res.status(400);
    res.json((err as Error).message);
  }
};

/**
 * Shows a specific user by their ID
 *
 * @param {Request} req - The request object containing the user ID 
 * @param {Response} res - The response object used to send the user information
 */
const show = async (req: Request, res: Response) => {
  try {
    //
    const user = await store.show(req.params.id);
    res.json(user);
  } catch (err) {
    res.status(400);
    res.json((err as Error).message);
  }
};

/**
 * Creates a new user and generates a JWT token for them
 * 
 * @param {Request} req - The request object containing the user information to create
 * @param {Response} res - The response object used to send the token 
 */
const create = async (req: Request, res: Response) => {
  try {
    const user: User = {
      // Get the user data from the request body
      username: req.body.username,
      firstName: req.body.firstName,
      lastName: req.body.lastName,
      password: req.body.password,
    };
    const newUser = await store.create(user);
    // Create a token for a new user, which can be used for an authentication and subsequent HTTP requests
    // The token is generated by signing the user object with a token secret obtained from environment variables
    var token = jwt.sign({ user: newUser }, process.env.TOKEN_SECRET as string);
    res.json(token);
  } catch (err) {
    res.status(400);
    res.json((err as Error).message);
  }
};


/**
 * Authenticates a user by checking their credentials and generating a JWT token
 * 
 * @param {Request} req - The request object containing the user information to authenticate 
 * @param {Response} res - The response object used to send the token 
 */
const authenticate = async (req: Request, res: Response) => {
  try {
    const user: User = {
      // Get the user data from the request body
      username: req.body.username,
      firstName: req.body.firstName,
      lastName: req.body.lastName,
      password: req.body.password,
    };

    // Authenticate the user by checking their credentials and save the authed user object or null in a variable
    const u = await store.authenticate(user.username, user.password);

    // If the user is not found, return a warning message
    if (!u) {
      return res.status(401).json('Wrong username-password');
    }

    // Create a token for the authenticated user, which can be used for authentication and subsequent HTTP requests
    // The token is generated by signing the user object with a token secret obtained from environment variables
    let token = jwt.sign({ user: u }, process.env.TOKEN_SECRET as string);
    //console.log ('authenticate',{ user: u });
    res.json(token);
  } catch (err) {
    res.status(400);
    res.json((err as Error).message);
  }
};

/**
 * Updates a user by their ID 
 *
 * @param {Request} req - The request object containing the user information to update
 * @param {Response} res - The response object used to send the updated user information
 */
const update = async (req: Request, res: Response) => {
  try {
    const user: UserWithID = {
      // Get the user data from the request body
      id: Number(req.params.id),
      username: req.body.username,
      firstName: req.body.firstName,
      lastName: req.body.lastName,
      password: req.body.password,
    };

    // Call the update method of the store object to update the user
    const updateUser = await store.update(user);
    res.json(updateUser);
  } catch (err) {
    res.status(400);
    res.json((err as Error).message);
  }
};


/**
 * Deletes a user by their ID
 * 
 * @param {Request} req - The request object containing the user ID to delete
 * @param {Response} res - The response object used to send the deleted user information
 */
const del = async (req: Request, res: Response) => {
  try {
    // Call the delete method of the store object to delete the user
    const deleted = await store.delete(req.params.id);
    res.json(deleted);
  } catch (err) {
    res.status(400);
    res.json((err as Error).message);
  }
};

// Express routes here

/**
 * Routes for user endpoints
 * 
 * @param {express.Application} app - The express application object 
 */
const userRoutes = (app: express.Application) => {
  // Route to show all users using middleware to verify the token
  app.get('/users', verifyAuthToken, index), 

  // Route to show a specific user using middleware to verify the token
  app.get('/users/:id', verifyAuthToken, show), 

  // Route to create a new user
  app.post('/users', create), 

  // Route to authenticate a user
  app.post('/users/authenticate', authenticate), 

  // Route to update a user using middleware to verify the token
  app.put('/users/:id', verifyAuthToken, update), 
  
  // Route to delete a user using middleware to verify the token
  app.delete('/users/:id', verifyAuthToken, del);
};

export default userRoutes;
